### ISSUE TITLE
Getting this `server` error upon trying to start

### ISSUE THREAD

**Issue by legendarykamal** [Rate-Limiting-Nullifier/zk-chat-client-server#9]
![image](https://user-images.githubusercontent.com/95926324/230548172-3f6d6f31-9b23-47ed-b133-721ef7502af1.png)

```
/workspaces/zk-chat-client-server/server (main) $ yarn start
yarn run v1.22.19
$ node .
/workspaces/zk-chat-client-server/node_modules/uWebSockets.js/uws.js:22
                throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
                ^

Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_linux_x64_111.node'
Require stack:
- /workspaces/zk-chat-client-server/node_modules/uWebSockets.js/uws.js
- /workspaces/zk-chat-client-server/node_modules/zk-chat-server/dist/index.node.js
- /workspaces/zk-chat-client-server/server/dist/src/create_server.js
- /workspaces/zk-chat-client-server/server/dist/src/index.js
    at /workspaces/zk-chat-client-server/node_modules/uWebSockets.js/uws.js:22:9
    at Object.<anonymous> (/workspaces/zk-chat-client-server/node_modules/uWebSockets.js/uws.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/workspaces/zk-chat-client-server/node_modules/zk-chat-server/dist/index.node.js:15:11)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)

Node.js v19.7.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by legendarykamal** [comment]
@NicoSerranoP
 @AtHeartEngineer
 any ideas how to resolve this ?

**Comment by AtHeartEngineer** [comment]
Hey! We are currently modifying this project for a particular event, if you go back a few commits, maybe it should work?

Also, use node 16 not node 18+.

**Comment by NicoSerranoP** [comment]
@legendarykamal did it work? I just started the server in the main branch using node 16.20.0 in Windows. If you need, this tool can help you manage your node versions: 

Windows: https://github.com/coreybutler/nvm-windows

Linux: https://www.npmjs.com/package/n

**Comment by legendarykamal** [comment]
Hey @NicoSerranoP , Yes it worked by moving to an earlier node version. Thanks.
